# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jose Eduardo Silva Canizales
title: Estudiante de ingeniería en informática
email: jose.silva5168@alumnos.udg.mx
website: https://github.com/Eduardosscc21/Eduardosscc21.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: N/A
github_username: Eduardosscc21
instagram_username: N/A
linkedin_username: N/A
youtube_username: N/A

# Additional icon links
additional_links:
  - title: itsgoingto.be
    icon: fas fa-globe
    url: https://www.itsgoingto.be

# About Section
about_profile_image: images/profile.jpg
about_content: |
  Hola, mi nombre es Eduardo. Soy estudiante de ingeniería en informática en la UDG, y tengo experiencia como desarrollador backend y frontend.
  Lo que mejor sé hacer es: <mark>durmiendo</mark> y <mark>comiendo pizza</mark>.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme

  - title: Experience
    layout: list
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present

  - title: Education
    layout: list
    content:
      - layout: left
        title: Centro Universitario de Ciencias Exactas e Ingenierías
        caption: 2021 - presente
        sub_title: Ingeniería en informática
        quote: >
          El Centro Universitario de Ciencias Exactas e Ingenierías es la división de la Universidad de Guadalajara en Jalisco, México, destinada a la educación superior relacionada con los campos de ingenierías, ciencias físicas, químicas y matemáticas.
        description: |
          Durante mi estancia en CUCEI, he aprendido diversos conocimientos como matemáticas discretas, planeación de proyectos y he ido desarrollando habilidades de Full Stack.

          Además, como complemento a mi educación, he tomado diversos cursos, como:

  - title: A Little More About Me
    layout: text
    content: |
      Junto a mi interés en redes y desarrollo de software, algunos de mis otros intereses y hobbies son:
      - Jugar videojuegos
      - Tejer
      - [Convertirme en ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      ¡Mira esta imagen genial!


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

