# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jose Eduardo Silva Canizales
title: Estudiante de ingenieria en informatica
email: jose.silva5168@alumnos.udg.mx
website: https://github.com/Eduardosscc21/Eduardosscc21.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: N/A
github_username: Eduardosscc21
instagram_username: N/A
linkedin_username: N/A
youtube_username: N/A

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be

# About Section
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hola mi nombre es eduardo soy estudiante de ingenieria en informatica en la udg, tengo algo de experiencia como desarrollador backend y frontend. 
  En lo que soy mejor es : <mark>durmiendo </mark> y <mark>comiendo Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present

  - title: Education
    layout: list
    content:
      - layout: left
        title: Centro Universitario de Ciencias Exactas e Ingenierías.
        caption: 2021 - presente
        sub_title: Ingeniería en informática
        quote: >
          El Centro Universitario de Ciencias Exactas e Ingenierías es la división de la Universidad de Guadalajara en Jalisco, México, destinada a la educación superior relacionada con los campos de ingenierías, ciencias físicas, químicas y matemáticas.
        description: |
          Durante mi estancia en CUCEI, he aprendido diversos conocimientos tales como matemáticas discretas, planeación de proyectos y poco a poco he ido desarrollando habilidades de Full Stack.

          Por otra parte, como complemento a mi educación, he tomado diversos cursos, tales como:
        - layout: top-middle
            title: Cloud Core
            image: /images/cloud-core.png
            image_alt: Cloud Core
            image_title: Cloud Core
        - layout: top-middle
            title: Advanced Kubernetes Operators
            image: /images/advanced-kubernetes-operators.png
            image_alt: Advanced Kubernetes Operators
            image_title: Advanced Kubernetes Operators
        - layout: top-middle
            title: Containers Kubernetes Essentials
            image: /images/containers-kubernetes-essentials.png
            image_alt: Containers Kubernetes Essentials
            image_title: Containers Kubernetes Essentials
        - layout: top-middle
            title: Data Science for Business Level 1
            image: /images/data-science-for-business-level-1.png
            image_alt: Data Science for Business Level 1
            image_title: Data Science for Business Level 1
        - layout: top-middle
            title: Data Science Foundations Level 1
            image: /images/data-science-foundations-level-1.png
            image_alt: Data Science Foundations Level 1
            image_title: Data Science Foundations Level 1
        - layout: top-middle
            title: Data Science Methodologies
            image: /images/data-science-methodologies.png
            image_alt: Data Science Methodologies
            image_title: Data Science Methodologies
        - layout: top-middle
            title: Data Science Tools
            image: /images/data-science-tools.png
            image_alt: Data Science Tools
            image_title: Data Science Tools
        - layout: top-middle
            title: Docker Essentials: A Developer Introduction
            image: /images/docker-essentials-a-developer-introduction.png
            image_alt: Docker Essentials: A Developer Introduction
            image_title: Docker Essentials: A Developer Introduction
        - layout: top-middle
            title: Intermediate Kubernetes Operators
            image: /images/intermediate-kubernetes-operators.png
            image_alt: Intermediate Kubernetes Operators
            image_title: Intermediate Kubernetes Operators

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

